dist: xenial
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
apt_packages:
  - libgdal-dev
  - libudunits2-dev
  - cargo
  - libpoppler-cpp-dev
cache:
  packages
  
git:
  depth: false
 
r_packages:
 
r_github_packages: rensa/ggflags

script:
  - R -f deploy.r
